import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { InMemoryTransport } from '@modelcontextprotocol/sdk/inMemory.js';
import type { Tool } from '@modelcontextprotocol/sdk/types.js';
import { FireFinderClient } from '@firefinder/client';
import { renderPluginHooks } from './claude-code-plugin.ts';
import { FIREFINDER_INSTRUCTIONS } from './instructions.ts';
import { createFireFinderMcpServer } from './server.ts';

async function listTools(): Promise<Tool[]> {
  const server = createFireFinderMcpServer(new FireFinderClient({ baseUrl: 'http://unused', apiKey: 'unused' }));
  const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
  await server.connect(serverTransport);
  const client = new Client({ name: 'firefinder-exporter', version: '1.0.0' });
  await client.connect(clientTransport);
  const { tools } = await client.listTools();
  await client.close();
  return tools;
}

/**
 * Everything generated from the MCP server's own definitions, so every
 * integration describes FireFinder identically:
 *  - integrations/claude/tools.json + system-prompt.md (Claude Messages API)
 *  - plugins/firefinder/skills/firefinder/SKILL.md (Claude Code plugin)
 *  - plugins/firefinder/hooks/ (Claude Code plugin, failed-command hook)
 *  - plugins/firefinder/evals{,-shell}/mocks/firefinder/_tools.json (plugin evals)
 *  - plugins/firefinder-desktop/skills/firefinder/SKILL.md + evals mocks (Claude desktop app plugin)
 *  - plugins/firefinder-codex/skills/firefinder/SKILL.md (Codex and ChatGPT plugin)
 */
export async function renderClaudeExports(): Promise<{
  tools: string;
  systemPrompt: string;
  pluginSkill: string;
  pluginHooks: string;
  pluginHookHint: string;
  pluginToolsList: string;
  pluginShellEvalToolsList: string;
  desktopPluginSkill: string;
  desktopPluginToolsList: string;
  codexPluginSkill: string;
}> {
  const tools = await listTools();

  const definitions = tools.map((tool) => {
    const { $schema: _schemaVersion, ...inputSchema } = tool.inputSchema as Record<string, unknown>;
    return { name: tool.name, description: tool.description, input_schema: inputSchema };
  });

  const systemPrompt = [
    '# FireFinder system prompt for Claude',
    '',
    '<!-- Generated by `npm run export:claude` from packages/mcp/src/instructions.ts. Do not edit by hand. -->',
    '',
    'Use this as (part of) the system prompt when you give Claude the tools in `tools.json` through the Messages API.',
    'MCP clients (claude.ai, Claude Desktop, Claude Code) receive the same guidance automatically when they connect.',
    '',
    '```text',
    FIREFINDER_INSTRUCTIONS,
    '```',
    '',
  ].join('\n');

  const pluginSkill = [
    '---',
    'name: firefinder',
    'description: >-',
    '  Use automatically, without being asked, at two moments. (1) BEFORE answering whenever the user is stuck',
    '  on a practical problem others plausibly hit too, technical (error, crash, failing build/install/deploy,',
    '  broken setting, app or device) or everyday (stain, household repair, appliance, car, travel or booking',
    '  snag, paperwork), or when a command you run fails with an install, dependency, build or environment',
    '  error others hit too: search FireFinder\'s shared memory of verified fixes first. (2) As soon as the',
    '  user says a fix worked or failed, however casually ("this worked", "amazing, that worked!", "that did',
    '  it", "still broken"): record it. Not for general questions, writing, math, small talk, or health,',
    '  legal, financial or relationship matters.',
    '---',
    '',
    '<!-- Generated by `npm run export:claude` from packages/mcp/src/instructions.ts. Do not edit by hand. -->',
    '',
    '# FireFinder',
    '',
    'The FireFinder tools come from this plugin\'s `firefinder` MCP server, or from a claude.ai FireFinder connector if one is connected. They are the same tools.',
    '',
    FIREFINDER_INSTRUCTIONS,
    '',
    '## In Claude Code',
    '',
    '- Failed commands count too. When a command you run fails with an error others plausibly hit (dependency, install, build tool, runtime or SDK version, environment, configuration, network, auth, deploy), search before trying fixes, once per distinct problem. Skip bugs in the code being worked on and expected failures such as failing tests. This plugin\'s hook reminds you when a package manager, toolchain, container, deploy or git remote command fails.',
    '- A command that passes after a fix is not the user\'s words. Record an outcome only when the user says it worked or failed.',
    '- `/firefinder:search` and `/firefinder:fire` let the user search FireFinder or look up a fix directly. Answer those visibly, even when nothing matches.',
    '',
  ].join('\n');

  // The Claude desktop app (Cowork) plugin: the same guidance, without the Claude Code parts.
  const desktopPluginSkill = [
    '---',
    'name: firefinder',
    'description: >-',
    '  Use automatically, without being asked, at two moments. (1) BEFORE answering whenever the user is stuck',
    '  on a practical problem others plausibly hit too, technical (error, crash, failing build/install/deploy,',
    '  broken setting, app or device) or everyday (stain, household repair, appliance, car, travel or booking',
    '  snag, paperwork): search FireFinder\'s shared memory of verified fixes first. (2) As soon as the user says',
    '  a fix worked or failed, however casually ("this worked", "amazing, that worked!", "that did it",',
    '  "still broken"): record it. Not for general questions, writing, math, small talk, or health, legal,',
    '  financial or relationship matters.',
    '---',
    '',
    '<!-- Generated by `npm run export:claude` from packages/mcp/src/instructions.ts. Do not edit by hand. -->',
    '',
    '# FireFinder',
    '',
    'The FireFinder tools come from this plugin\'s `firefinder` connector, or from a FireFinder connector the user added to the app. They are the same tools.',
    '',
    FIREFINDER_INSTRUCTIONS,
    '',
    '## Commands',
    '',
    'The user can also use FireFinder by hand with `/firefinder:search`, `/firefinder:fire`, `/firefinder:worked`, `/firefinder:failed` and `/firefinder:help`, which have their own instructions. Record each outcome once: after you have recorded a fix automatically, a later `/firefinder:worked` for the same fix doesn\'t record it again, and after a command has recorded it, you don\'t either.',
    '',
  ].join('\n');

  // The Codex and ChatGPT plugin: one package for both. Hooks don't run in ChatGPT chat and Codex
  // has no failed-tool event, so the failed-command guidance lives here instead of in a hook.
  const codexPluginSkill = [
    '---',
    'name: firefinder',
    'description: >-',
    '  Use automatically, without being asked, at two moments. (1) BEFORE answering whenever the user is stuck',
    '  on a practical problem others plausibly hit too, technical (error, crash, failing build/install/deploy,',
    '  broken setting, app or device) or everyday (stain, household repair, appliance, car, travel or booking',
    '  snag, paperwork), or when a command you run fails with an install, dependency, build or environment',
    '  error others hit too: search FireFinder\'s shared memory of verified fixes first. (2) As soon as the',
    '  user says a fix worked or failed, however casually ("this worked", "amazing, that worked!", "that did',
    '  it", "still broken"): record it. Not for general questions, writing, math, small talk, or health,',
    '  legal, financial or relationship matters.',
    '---',
    '',
    '<!-- Generated by `npm run export:claude` from packages/mcp/src/instructions.ts. Do not edit by hand. -->',
    '',
    '# FireFinder',
    '',
    'The FireFinder tools come from this plugin\'s `firefinder` MCP server, or from a FireFinder app the user connected in ChatGPT. They are the same tools.',
    '',
    FIREFINDER_INSTRUCTIONS,
    '',
    '## When you run commands (Codex, ChatGPT Work)',
    '',
    '- Failed commands count too. When a command you run fails with an error others plausibly hit (dependency, install, build tool, runtime or SDK version, environment, configuration, network, auth, deploy), search before trying fixes, once per distinct problem. Skip bugs in the code being worked on and expected failures such as failing tests.',
    '- A command that passes after a fix is not the user\'s words. Record an outcome only when the user says it worked or failed.',
    '',
    '## Explicit requests',
    '',
    'The user can also use FireFinder by hand through this plugin\'s `search`, `fire`, `worked`, `failed` and `help` skills, which have their own instructions. Record each outcome once: after you have recorded a fix automatically, a later `worked` request for the same fix doesn\'t record it again, and after one of those skills has recorded it, you don\'t either.',
    '',
  ].join('\n');

  const toolsList = `${JSON.stringify({ tools }, null, 2)}\n`;
  const { hooks: pluginHooks, hint: pluginHookHint } = renderPluginHooks();

  return {
    tools: `${JSON.stringify(definitions, null, 2)}\n`,
    systemPrompt,
    pluginSkill,
    pluginHooks,
    pluginHookHint,
    pluginToolsList: toolsList,
    pluginShellEvalToolsList: toolsList,
    desktopPluginSkill,
    desktopPluginToolsList: toolsList,
    codexPluginSkill,
  };
}
