import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { InMemoryTransport } from '@modelcontextprotocol/sdk/inMemory.js';
import type { Tool } from '@modelcontextprotocol/sdk/types.js';
import { FireFinderClient } from '@firefinder/client';
import { FIREFINDER_INSTRUCTIONS } from './instructions.ts';
import { createFireFinderMcpServer } from './server.ts';

async function listTools(): Promise<Tool[]> {
  const server = createFireFinderMcpServer(new FireFinderClient({ baseUrl: 'http://unused', apiKey: 'unused' }));
  const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
  await server.connect(serverTransport);
  const client = new Client({ name: 'firefinder-exporter', version: '1.0.0' });
  await client.connect(clientTransport);
  const { tools } = await client.listTools();
  await client.close();
  return tools;
}

/**
 * Everything generated from the MCP server's own definitions, so every
 * integration describes FireFinder identically:
 *  - integrations/claude/tools.json + system-prompt.md (Claude Messages API)
 *  - plugins/firefinder/skills/firefinder/SKILL.md (Claude Code plugin)
 *  - plugins/firefinder/evals/mocks/firefinder/_tools.json (plugin evals)
 */
export async function renderClaudeExports(): Promise<{
  tools: string;
  systemPrompt: string;
  pluginSkill: string;
  pluginToolsList: string;
}> {
  const tools = await listTools();

  const definitions = tools.map((tool) => {
    const { $schema: _schemaVersion, ...inputSchema } = tool.inputSchema as Record<string, unknown>;
    return { name: tool.name, description: tool.description, input_schema: inputSchema };
  });

  const systemPrompt = [
    '# FireFinder system prompt for Claude',
    '',
    '<!-- Generated by `npm run export:claude` from packages/mcp/src/instructions.ts. Do not edit by hand. -->',
    '',
    'Use this as (part of) the system prompt when you give Claude the tools in `tools.json` through the Messages API.',
    'MCP clients (claude.ai, Claude Desktop, Claude Code) receive the same guidance automatically when they connect.',
    '',
    '```text',
    FIREFINDER_INSTRUCTIONS,
    '```',
    '',
  ].join('\n');

  const pluginSkill = [
    '---',
    'name: firefinder',
    'description: >-',
    '  Use automatically, without being asked, at two moments. (1) BEFORE answering whenever the user is stuck',
    '  on a practical problem others plausibly hit too, technical (error, crash, failing build/install/deploy,',
    '  broken setting, app or device) or everyday (stain, household repair, appliance, car, travel or booking',
    '  snag, paperwork): search FireFinder\'s shared memory of verified fixes first. (2) As soon as the user says',
    '  a fix worked or failed, however casually ("this worked", "amazing, that worked!", "that did it",',
    '  "still broken"): record it. Not for general questions, writing, math, small talk, or health, legal,',
    '  financial or relationship matters.',
    '---',
    '',
    '<!-- Generated by `npm run export:claude` from packages/mcp/src/instructions.ts. Do not edit by hand. -->',
    '',
    '# FireFinder',
    '',
    'The FireFinder tools come from this plugin\'s `firefinder` MCP server.',
    '',
    FIREFINDER_INSTRUCTIONS,
    '',
  ].join('\n');

  return {
    tools: `${JSON.stringify(definitions, null, 2)}\n`,
    systemPrompt,
    pluginSkill,
    pluginToolsList: `${JSON.stringify({ tools }, null, 2)}\n`,
  };
}
