/**
 * Bundles deployable artifacts with esbuild.
 *   node scripts/build.ts mcp    -> packages/mcp/dist/firefinder-mcp.js (single-file MCP server for Claude)
 *   node scripts/build.ts edge   -> supabase/functions/firefinder/index.js (Supabase Edge Function)
 */
import { readFileSync } from 'node:fs';
import { build, type Plugin } from 'esbuild';

const target = process.argv[2];

async function buildMcp() {
  await build({
    entryPoints: ['packages/mcp/src/cli.ts'],
    outfile: 'packages/mcp/dist/firefinder-mcp.js',
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node20',
    legalComments: 'none',
    // Some bundled CommonJS dependencies call require() for Node built-ins.
    banner: { js: "import { createRequire as __ffCreateRequire } from 'node:module'; const require = __ffCreateRequire(import.meta.url);" },
  });
  console.log('built packages/mcp/dist/firefinder-mcp.js');
}

async function buildEdge() {
  const postgresVersion = JSON.parse(readFileSync('apps/api/package.json', 'utf8')).dependencies.postgres as string;
  // postgres.js stays an npm: import so Deno loads its Deno-compatible build.
  const npmSpecifiers: Plugin = {
    name: 'npm-specifiers',
    setup(pluginBuild) {
      pluginBuild.onResolve({ filter: /^postgres$/ }, () => ({ path: `npm:postgres@${postgresVersion}`, external: true }));
    },
  };
  await build({
    entryPoints: ['apps/edge/src/main.ts'],
    outfile: 'supabase/functions/firefinder/index.js',
    bundle: true,
    platform: 'neutral',
    format: 'esm',
    target: 'es2022',
    mainFields: ['module', 'main'],
    conditions: ['deno', 'worker', 'import', 'default'],
    plugins: [npmSpecifiers],
    // Smaller bundle = faster cold starts. keepNames preserves error class names.
    minify: true,
    keepNames: true,
    legalComments: 'none',
    banner: { js: '// Generated by `npm run build:edge` from apps/edge/src/main.ts. Do not edit by hand.' },
  });
  console.log('built supabase/functions/firefinder/index.js');
}

if (target === 'mcp') await buildMcp();
else if (target === 'edge') await buildEdge();
else {
  console.error('usage: node scripts/build.ts <mcp|edge>');
  process.exit(1);
}
