-- =============================================================================
-- FireFinder schema
-- Solve a problem once -> remember the solution -> help everyone who hits it.
--
-- Portable by design: plain PostgreSQL 15+ with pgvector >= 0.7. Nothing here
-- depends on Supabase, but when Supabase's Data API roles (anon, authenticated)
-- exist they are explicitly locked out. All access goes through the FireFinder
-- API, which connects as the schema owner.
--
-- The script is idempotent so it can be applied by `supabase db push` or by
-- `npm run db:migrate` (self-hosted) without conflict.
-- =============================================================================

create schema if not exists extensions;
create extension if not exists vector with schema extensions;

-- A dedicated schema keeps FireFinder out of Supabase's auto-generated REST API
-- (which only exposes `public` by default).
create schema if not exists firefinder;
comment on schema firefinder is
  'FireFinder shared solution memory. Accessed only through the FireFinder API.';

-- -----------------------------------------------------------------------------
-- solutions: one verified (or candidate) problem/solution pair, a "fire".
-- -----------------------------------------------------------------------------
create table if not exists firefinder.solutions (
  -- UUIDv7 generated by the API so records stay globally unique across
  -- self-hosted instances and future community mirrors.
  id uuid primary key default gen_random_uuid(),
  -- Short human-friendly number used in the UI: "FIRE #18492".
  fire_number bigint generated always as identity unique,

  problem text not null,
  solution text not null,
  software text,
  operating_system text,
  software_version text,
  error_message text,

  -- Normalized metadata computed by the API and used for matching/ranking.
  software_key text,
  os_family text,
  os_version text,
  version_major text,
  error_signature text[] not null default '{}',

  confirmation_count integer not null default 0,
  failure_count integer not null default 0,
  -- Moderation state. Disabled solutions are never returned.
  status text not null default 'active',
  -- A submission is only a candidate until at least one person confirms it.
  verification_status text generated always as (
    case when confirmation_count > 0 then 'verified' else 'candidate' end
  ) stored,

  -- gte-small embedding of the problem (+ error, software) for semantic search.
  embedding extensions.vector(384) not null,
  -- gte-small embedding of the solution text, used for duplicate detection.
  solution_embedding extensions.vector(384) not null,
  embedding_model text not null,
  -- Which integration submitted it (e.g. "claude-mcp"). Never a person.
  source text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_confirmed_at timestamptz,
  last_failed_at timestamptz,

  constraint solutions_problem_length check (char_length(problem) between 3 and 1000),
  constraint solutions_solution_length check (char_length(solution) between 3 and 5000),
  constraint solutions_software_length check (char_length(software) <= 100),
  constraint solutions_os_length check (char_length(operating_system) <= 100),
  constraint solutions_version_length check (char_length(software_version) <= 50),
  constraint solutions_error_length check (char_length(error_message) <= 1000),
  constraint solutions_source_length check (char_length(source) <= 40),
  constraint solutions_status_check check (status in ('active', 'under_review', 'disabled')),
  constraint solutions_counts_nonnegative check (confirmation_count >= 0 and failure_count >= 0),
  constraint solutions_error_signature_size check (cardinality(error_signature) <= 16)
);

comment on table firefinder.solutions is
  'Problem/solution pairs. Only generalized, privacy-filtered text is stored; never conversations.';

-- Approximate nearest-neighbour search on the problem embedding.
create index if not exists solutions_embedding_hnsw_idx
  on firefinder.solutions using hnsw (embedding extensions.vector_cosine_ops);

-- Exact error-code matching (ERR_OSSL_EVP_UNSUPPORTED, 0x80070005, ...).
create index if not exists solutions_error_signature_idx
  on firefinder.solutions using gin (error_signature);

-- Moderation queue: the (small) set of solutions that are not active.
create index if not exists solutions_moderation_idx
  on firefinder.solutions (status, updated_at desc)
  where status <> 'active';

create or replace function firefinder.touch_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create or replace trigger solutions_touch_updated_at
  before update on firefinder.solutions
  for each row execute function firefinder.touch_updated_at();

-- -----------------------------------------------------------------------------
-- solution_confirmations: one row per "it worked" / "it didn't work" vote.
-- voter_hash is an HMAC of an anonymous client identifier: it lets us count
-- one vote per voter without knowing who anyone is.
-- -----------------------------------------------------------------------------
create table if not exists firefinder.solution_confirmations (
  id bigint generated always as identity primary key,
  solution_id uuid not null references firefinder.solutions (id) on delete cascade,
  result text not null,
  voter_hash text,
  -- Optional environment of the voter; helps moderators see *where* a fix fails.
  operating_system text,
  software_version text,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint confirmations_result_check check (result in ('worked', 'failed')),
  constraint confirmations_voter_hash_format check (voter_hash ~ '^[0-9a-f]{64}$'),
  constraint confirmations_os_length check (char_length(operating_system) <= 100),
  constraint confirmations_version_length check (char_length(software_version) <= 50),
  constraint confirmations_note_length check (char_length(note) <= 500)
);

-- Foreign-key index; also serves "latest feedback for a solution".
create index if not exists solution_confirmations_solution_idx
  on firefinder.solution_confirmations (solution_id, created_at desc);

-- One vote per anonymous voter per solution.
create unique index if not exists solution_confirmations_voter_idx
  on firefinder.solution_confirmations (solution_id, voter_hash)
  where voter_hash is not null;

-- -----------------------------------------------------------------------------
-- api_keys: server-to-server credentials. Only a SHA-256 hash is stored.
-- -----------------------------------------------------------------------------
create table if not exists firefinder.api_keys (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  key_prefix text not null,
  key_hash text not null unique,
  scopes text[] not null default array['read', 'write'],
  created_at timestamptz not null default now(),
  last_used_at timestamptz,
  revoked_at timestamptz,

  constraint api_keys_name_length check (char_length(name) between 1 and 100),
  constraint api_keys_hash_format check (key_hash ~ '^[0-9a-f]{64}$'),
  constraint api_keys_scopes_check check (
    cardinality(scopes) > 0 and scopes <@ array['read', 'write', 'admin']
  )
);

-- -----------------------------------------------------------------------------
-- rate_limit_buckets: fixed-window counters for the Postgres-backed limiter
-- (used where the API runs as many short-lived instances, e.g. Edge Functions).
-- Unlogged: fast, and losing counters on a crash is harmless.
-- -----------------------------------------------------------------------------
create unlogged table if not exists firefinder.rate_limit_buckets (
  bucket_key text not null,
  window_start timestamptz not null,
  hits integer not null default 0,
  primary key (bucket_key, window_start)
);

-- =============================================================================
-- Functions
-- =============================================================================

-- Candidate retrieval for search and duplicate detection.
-- Hybrid: nearest neighbours by embedding UNION exact error-code matches.
-- Final ranking happens in the API (packages/core/src/ranking.ts) so it can
-- evolve without migrations.
create or replace function firefinder.search_candidates(
  p_embedding extensions.vector(384),
  p_error_signature text[],
  p_limit integer,
  p_solution_embedding extensions.vector(384) default null
)
returns table (
  id uuid,
  fire_number bigint,
  problem text,
  solution text,
  software text,
  operating_system text,
  software_version text,
  error_message text,
  software_key text,
  os_family text,
  os_version text,
  version_major text,
  error_signature text[],
  confirmation_count integer,
  failure_count integer,
  status text,
  verification_status text,
  created_at timestamptz,
  updated_at timestamptz,
  last_confirmed_at timestamptz,
  last_failed_at timestamptz,
  similarity double precision,
  solution_similarity double precision,
  error_overlap integer
)
language sql
stable
set search_path = ''
-- HNSW returns at most ef_search rows; keep it above any candidate limit we use.
set hnsw.ef_search = '100'
as $$
  with semantic as (
    select s.id
    from firefinder.solutions s
    where s.status <> 'disabled'
    order by s.embedding operator(extensions.<=>) p_embedding
    limit least(p_limit, 100)
  ),
  lexical as (
    select s.id
    from firefinder.solutions s
    where cardinality(p_error_signature) > 0
      and s.error_signature && p_error_signature
      and s.status <> 'disabled'
    order by s.confirmation_count desc
    limit least(p_limit, 100)
  ),
  candidate_ids as (
    select semantic.id from semantic
    union
    select lexical.id from lexical
  )
  select
    s.id, s.fire_number, s.problem, s.solution,
    s.software, s.operating_system, s.software_version, s.error_message,
    s.software_key, s.os_family, s.os_version, s.version_major, s.error_signature,
    s.confirmation_count, s.failure_count, s.status, s.verification_status,
    s.created_at, s.updated_at, s.last_confirmed_at, s.last_failed_at,
    1 - (s.embedding operator(extensions.<=>) p_embedding) as similarity,
    case
      when p_solution_embedding is null then null
      else 1 - (s.solution_embedding operator(extensions.<=>) p_solution_embedding)
    end as solution_similarity,
    cardinality(array(
      select unnest(s.error_signature)
      intersect
      select unnest(p_error_signature)
    )) as error_overlap
  from candidate_ids c
  join firefinder.solutions s on s.id = c.id;
$$;

-- Record "worked" / "failed" feedback atomically.
-- * One vote per voter per solution; a voter may change their vote.
-- * Counters, last_confirmed_at and last_failed_at are updated together.
-- * Moderation hook: a solution that keeps failing is moved to under_review.
--   It is never deleted automatically; a fix may only fail in some environments.
create or replace function firefinder.record_feedback(
  p_solution_id uuid,
  p_result text,
  p_voter_hash text,
  p_operating_system text default null,
  p_software_version text default null,
  p_note text default null,
  p_review_min_failures integer default 5,
  p_review_failure_ratio double precision default 0.75
)
returns table (outcome text, previous_result text)
language plpgsql
volatile
set search_path = ''
as $$
declare
  v_status text;
  v_vote_id bigint;
  v_previous text;
begin
  if p_result is null or p_result not in ('worked', 'failed') then
    raise exception 'invalid feedback result: %', p_result using errcode = '22023';
  end if;

  -- Lock the solution row: serializes feedback per solution, so counters and
  -- the one-vote-per-voter rule stay consistent under concurrency.
  select s.status into v_status
  from firefinder.solutions s
  where s.id = p_solution_id
  for update;

  if not found or v_status = 'disabled' then
    return query select 'not_found'::text, null::text;
    return;
  end if;

  if p_voter_hash is not null then
    select c.id, c.result into v_vote_id, v_previous
    from firefinder.solution_confirmations c
    where c.solution_id = p_solution_id and c.voter_hash = p_voter_hash;
  end if;

  if v_previous = p_result then
    return query select 'duplicate'::text, v_previous;
    return;
  end if;

  if v_vote_id is not null then
    update firefinder.solution_confirmations c
    set result = p_result,
        operating_system = p_operating_system,
        software_version = p_software_version,
        note = p_note,
        updated_at = now()
    where c.id = v_vote_id;
  else
    insert into firefinder.solution_confirmations
      (solution_id, result, voter_hash, operating_system, software_version, note)
    values
      (p_solution_id, p_result, p_voter_hash, p_operating_system, p_software_version, p_note);
  end if;

  update firefinder.solutions s
  set confirmation_count = s.confirmation_count
        + (case when p_result = 'worked' then 1 else 0 end)
        - (case when v_previous = 'worked' then 1 else 0 end),
      failure_count = s.failure_count
        + (case when p_result = 'failed' then 1 else 0 end)
        - (case when v_previous = 'failed' then 1 else 0 end),
      last_confirmed_at = case when p_result = 'worked' then now() else s.last_confirmed_at end,
      last_failed_at = case when p_result = 'failed' then now() else s.last_failed_at end
  where s.id = p_solution_id;

  update firefinder.solutions s
  set status = 'under_review'
  where s.id = p_solution_id
    and s.status = 'active'
    and s.failure_count >= p_review_min_failures
    and s.failure_count::double precision
        / (s.failure_count + s.confirmation_count) >= p_review_failure_ratio;

  return query
    select (case when v_previous is null then 'recorded' else 'changed' end)::text, v_previous;
end;
$$;

-- Fixed-window rate limit counter. Returns the number of hits in the current
-- window including this one.
create or replace function firefinder.rate_limit_hit(
  p_key text,
  p_window_seconds integer
)
returns integer
language plpgsql
volatile
set search_path = ''
as $$
declare
  v_window timestamptz :=
    to_timestamp(floor(extract(epoch from now()) / p_window_seconds) * p_window_seconds);
  v_hits integer;
begin
  insert into firefinder.rate_limit_buckets as b (bucket_key, window_start, hits)
  values (p_key, v_window, 1)
  on conflict (bucket_key, window_start) do update set hits = b.hits + 1
  returning b.hits into v_hits;

  -- Opportunistic cleanup keeps the table tiny without needing a cron job.
  if random() < 0.01 then
    delete from firefinder.rate_limit_buckets
    where window_start < now() - interval '1 hour';
  end if;

  return v_hits;
end;
$$;

-- =============================================================================
-- Security
-- =============================================================================

-- Row-level security as defense in depth. There are deliberately no policies:
-- any role other than the owner (the API) sees nothing.
alter table firefinder.solutions enable row level security;
alter table firefinder.solution_confirmations enable row level security;
alter table firefinder.api_keys enable row level security;
alter table firefinder.rate_limit_buckets enable row level security;

-- Functions are executable by PUBLIC by default in Postgres; revoke that.
revoke all on schema firefinder from public;
revoke execute on all functions in schema firefinder from public;
alter default privileges in schema firefinder revoke execute on functions from public;

do $$
begin
  -- Supabase Data API roles: no access to anything FireFinder stores.
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on schema firefinder from anon';
    execute 'revoke all on all tables in schema firefinder from anon';
    execute 'revoke all on all functions in schema firefinder from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on schema firefinder from authenticated';
    execute 'revoke all on all tables in schema firefinder from authenticated';
    execute 'revoke all on all functions in schema firefinder from authenticated';
  end if;
end;
$$;
